server:
  port: 4000

spring:
  application:
    name: delivery-system-backend

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:sqlserver://DESKTOP-PO7GJL8:1434;databaseName=parcels_db_test;encrypt=false;trustServerCertificate=true;
    username: parcels_db_user
    password: password!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/delivery-system

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /api-docs/swagger-config
    url: /api-docs
    operations-sorter: method

keycloak:
  server-url: http://localhost:8180
  realm: delivery-system
  client-id: delivery-system-backend
  client-secret: sUS2ONeV5JJSuFWvmmbN3tPGHYjLWHmx

logging:
  level:
    root: INFO
    org.deliverysystem.com: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.transaction: INFO