input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/drivers/mssql-jdbc-13.4.0.jre11.jar"
    jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    jdbc_connection_string => "jdbc:sqlserver://host.docker.internal:1434;databaseName=parcels_db_test;encrypt=false;trustServerCertificate=true"
    jdbc_user => "parcels_db_user"
    jdbc_password => "password!"
    schedule => "*/5 * * * *"
    statement => "
      SELECT
        r.return_id,
        r.return_tracking_number,
        r.initiation_date,
        r.completion_date,
        r.refund_amount,
        rr.return_reason_name AS reason_name,
        s.shipment_tracking_number,
        s.shipment_total_price,
        origin_city.city_name AS origin_city,
        dest_city.city_name AS destination_city
      FROM returns r
      JOIN return_reasons rr ON r.return_reason_id = rr.return_reason_id
      JOIN shipments s ON r.shipment_id = s.shipment_id
      LEFT JOIN shipment_origin_delivery_points sodp ON s.shipment_id = sodp.shipment_id
      LEFT JOIN delivery_points origin_dp ON sodp.delivery_point_id = origin_dp.delivery_point_id
      LEFT JOIN cities origin_city ON origin_dp.city_id = origin_city.city_id
      LEFT JOIN shipment_destination_delivery_points sddp ON s.shipment_id = sddp.shipment_id
      LEFT JOIN delivery_points dest_dp ON sddp.delivery_point_id = dest_dp.delivery_point_id
      LEFT JOIN cities dest_city ON dest_dp.city_id = dest_city.city_id
      WHERE r.return_id > :sql_last_value
      ORDER BY r.return_id
    "
    tracking_column => "return_id"
    tracking_column_type => "numeric"
    use_column_value => true
    last_run_metadata_path => "/usr/share/logstash/.last_run_returns"
  }
}

filter {
  mutate {
    remove_field => ["@version"]
  }
  date {
    match => ["initiation_date", "ISO8601", "yyyy-MM-dd HH:mm:ss.SSS", "yyyy-MM-dd HH:mm:ss"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "returns"
    document_id => "%{return_id}"
  }
}